//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Silverlight.Weblog.Client.Default.Widgets;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private string _BlogName = string.Empty;

		public string BlogName
		{
			get
			{
				return this._BlogName;
			}

			set
			{
				if (this._BlogName != value)
				{
					this._BlogName = value;
					this.OnPropertyChanged("BlogName");
				}
			}
		}

		private string _BlogSubtitle = string.Empty;

		public string BlogSubtitle
		{
			get
			{
				return this._BlogSubtitle;
			}

			set
			{
				if (this._BlogSubtitle != value)
				{
					this._BlogSubtitle = value;
					this.OnPropertyChanged("BlogSubtitle");
				}
			}
		}

		private string _HomeUri = string.Empty;

		public string HomeUri
		{
			get
			{
				return this._HomeUri;
			}

			set
			{
				if (this._HomeUri != value)
				{
					this._HomeUri = value;
					this.OnPropertyChanged("HomeUri");
				}
			}
		}
	}
#endif
}
